---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adminer
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
#  - networkpolicy.yaml
  - ciliumnetworkpolicy.yaml
