---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: freshrss
resources:
  - namespace.yaml
  - freshrss-db-secret.yaml
  - freshrss-external-secret.yaml
  - freshrss-database.yaml
  - freshrss-configmap.yaml
  - freshrss-app.yaml
