---
apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: obsidian
  labels:
    app.kubernetes.io/name: obsidian-livesync
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: obsidian-livesync
    app.kubernetes.io/component: database
  ports:
    - port: 5984
      targetPort: 5984
      protocol: TCP
      name: http
